[Rainmeter]
Update=1000
DynamicWindowSize=1
BackgroundMode=2
SolidColor=0,0,0,1
MouseScrollUpAction=[!SetVariable size "(#size#+0.05)"][!WriteKeyValue Variables size "(#size#+0.05)"][!Refresh] 
MouseScrollDownAction=[!SetVariable size "(#size#-0.05 < 0.2 ? 0.2 : #size#-0.05)"][!WriteKeyValue Variables size "(#size#-0.05 < 0.2 ? 0.2 : #size#-0.05)"][!Refresh]


[Metadata]
Name=Iron Man Suite Time
Author=xenium
Version=1.0
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0


; � 2022 by xenium

[Variables]

@Include=#@#Variables.inc

size=1.15



;==========Measures===========

[MeasureWeekDay]
Measure=Time
Format=%A

[MeasureDate]
Measure=Time
Format=#DateFormat#

[MeasureTime]
Measure=Time
Format=#TimeFormat#

[MeasureAmPm]
Measure=#Ms#
Format=#Fm#

;==========Meters==============


[MeterClock]
Meter=STRING
MeasureName=MeasureTime
X=(#size#*450)
Y=(#size#*35)
FontColor=#ClockColor#
FontSize=(#size#*185)
FontFace=#FontClock#
StringAlign=center
StringStyle=normal
AntiAlias=1

[MeterAMPM]
Meter=STRING
MeasureName=MeasureAmPm
X=(#size#*650)
Y=(#size#*170)
FontEffectColor=#FontEffectColor#
FontSize=(#size#*50)
FontFace=#FontAMPM#
StringEffect=shadow
StringAlign=center
StringStyle=normal
AntiAlias=1
InlineSetting=GradientColor | 270 | #AMPMColor1# ; 0.2 | #AMPMColor2# ; 0.7
InlinePattern=.*

[MeterWeekDay]
Meter=STRING
MeasureName=MeasureWeekDay
X=(#size#*450)
Y=(#size#*260)
FontEffectColor=#FontEffectColor#
FontSize=(#size#*70)
FontFace=#FontWeekDay#
StringEffect=shadow
StringAlign=center
StringStyle=normal
AntiAlias=1
InlineSetting=GradientColor | 270 | #WeekDayColor1# ; 0.2 | #WeekDayColor2# ; 0.7
InlinePattern=.*

[MeterDate]
Meter=STRING
MeasureName=MeasureDate
X=(#size#*450)
Y=(#size#*340)
FontColor=#DateColor#
FontEffectColor=#FontEffectColor#
FontSize=(#size#*30)
FontFace=#FontDate#
StringEffect=shadow
StringAlign=center
StringStyle=Italic
AntiAlias=1
StringCase=Upper




; � 2022 by xenium












