; ----------------------------------

[Rainmeter]
Update=1000
Background=#@#Background.png
BackgroundMode=3
BackgroundMargins=0,36,0,14

[Metadata]
Name=Disk
Author=poiru
Information=Displays disk usage.
License=Creative Commons BY-NC-SA 3.0
Version=1.0.0

[Variables]
fontName=Segoe Script
textSize=12
colorBar=235,170,0,255
colorText=255,255,255,230
panelWidth=290
disk1=C:
disk2=D:

; ----------------------------------
; MEASURES
; ----------------------------------

[measureTotalDisk1]
Measure=FreeDiskSpace
Drive=#disk1#
Total=1
UpdateDivider=120

[measureUsedDisk1]
Measure=FreeDiskSpace
Drive=#disk1#
InvertMeasure=1
UpdateDivider=120

[measureTotalDisk2]
Measure=FreeDiskSpace
Drive=#disk2#
Total=1
UpdateDivider=120

[measureUsedDisk2]
Measure=FreeDiskSpace
Drive=#disk2#
InvertMeasure=1
UpdateDivider=120

; ----------------------------------
; STYLES
; ----------------------------------

[styleTitle]
StringAlign=Center
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,60
FontColor=#colorText#
FontFace=#fontName#
FontSize=16
AntiAlias=1
ClipString=1

[styleLeftText]
StringAlign=Left
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,30
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1

[styleRightText]
StringAlign=Right
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,30
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1

[styleBar]
BarColor=#colorBar#
BarOrientation=HORIZONTAL
SolidColor=255,255,255,18

; ----------------------------------
; METERS
; ----------------------------------

[meterTitle]
Meter=String
MeterStyle=styleTitle
X=(#panelWidth# / 2)
Y=4
W=#panelWidth#
H=26
Text=Disks

[meterLabelDisk1]
Meter=String
MeterStyle=styleLeftText
X=14
Y=42
W=50
H=20
Text=#disk1#\
LeftMouseUpAction=["#disk1#\"]

[meterValueDisk1]
Meter=String
MeterStyle=styleRightText
MeasureName=measureUsedDisk1
MeasureName2=measureTotalDisk1
X=(#panelWidth# - 14)
Y=0r
W=210
H=20
Text=%1B / %2B
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#disk1#\"]

[meterBarDisk1]
Meter=Bar
MeterStyle=styleBar
MeasureName=measureUsedDisk1
X=14
Y=64
W=(#panelWidth# - 28)
H=2

[meterLabelDisk2]
Meter=String
MeterStyle=styleLeftText
X=14
Y=76
W=50
H=20
Text=#disk2#\
LeftMouseUpAction=["#disk2#\"]

[meterValueDisk2]
Meter=String
MeterStyle=styleRightText
MeasureName=measureUsedDisk2
MeasureName2=measureTotalDisk2
X=(#panelWidth# - 14)
Y=0r
W=210
H=20
Text=%1B / %2B
NumOfDecimals=1
AutoScale=1
LeftMouseUpAction=["#disk2#\"]

[meterBarDisk2]
Meter=Bar
MeterStyle=styleBar
MeasureName=measureUsedDisk2
X=14
Y=98
W=(#panelWidth# - 28)
H=2
